ShoppingSite_FrontEnd.Site/Controllers/FaqsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ShoppingSite_FrontEnd.Site.Models.EFModels;

namespace ShoppingSite_FrontEnd.Site.Controllers
{
	public class FaqsController : Controller
	{
		private AppDbContext db = new AppDbContext();

		public ActionResult Index()
		{
			return View(db.Faqs.ToList());
		}
	}
}

ShoppingSite_FrontEnd.Site/Controllers/MembersController.cs
using ShoppingSite_FrontEnd.Site.Models.Core.Interfaces;
using ShoppingSite_FrontEnd.Site.Models.Core.Services;
using ShoppingSite_FrontEnd.Site.Models.Dtos;
using ShoppingSite_FrontEnd.Site.Models.EFModels;
using ShoppingSite_FrontEnd.Site.Models.Infrastructures.Repositories;
using ShoppingSite_FrontEnd.Site.Models.UseCases;
using ShoppingSite_FrontEnd.Site.Models.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace ShoppingSite_FrontEnd.Site.Controllers
{
	public class MembersController : Controller
	{
		private IMemberService _memberService;

		public MembersController()
		{
			var db = new AppDbContext();
			IMemberRepository repo = new MemberRepository(db);
			this._memberService = new MemberService(repo);
		}

		public ActionResult Register()
		{
			return View();
		}

		[HttpPost]
		public ActionResult Register(RegisterVM registerVM)
		{
			// 驗證欄位
			if (!ModelState.IsValid)
			{
				return View(registerVM);
			}

			// 呼叫 Command 來執行發信動作
			MemberCommand memberCommand = new MemberCommand(_memberService);
			RegisterResponse registerResponse = memberCommand.SendMail(registerVM);

			if (registerResponse.IsSuccess)
			{
				return View("RegisterConfirm");
			}
			else
			{
				ModelState.AddModelError(string.Empty, registerResponse.ErrorMessage);
				return View(registerVM);
			}
		}

		public ActionResult Login()
		{
			return View();
		}

		[HttpPost]
		public ActionResult Login(LoginVM loginVM)
		{
			LoginResponse loginResponse = _memberService.Login(loginVM.Account, loginVM.Password);
			
			// 如果登入成功，設定Cookie並轉址
			if (loginResponse.IsSuccess)
			{
				string returnUrl = ProcessLogin(loginVM.Account, out HttpCookie cookie);

				Response.Cookies.Add(cookie);

				return Redirect(returnUrl);
			}

			// 如果登入失敗，傳回錯誤訊息
			ModelState.AddModelError(string.Empty, loginResponse.ErrorMessage);
			return this.View(loginVM);
		}

		// 設定Cookie，給Login呼叫用
		private string ProcessLogin(string account, out HttpCookie cookie)
		{
			string roles = String.Empty;
			bool rememberMe = false;

			// 建立一張認證票
			FormsAuthenticationTicket ticket =
				new FormsAuthenticationTicket(
					1,          // 版本別, 沒特別用處
					account,
					DateTime.Now,   // 發行日
					DateTime.Now.AddDays(2), // 到期日
					rememberMe,     // 是否續存
					roles,          // userdata
					"/" // cookie位置
				);

			// 將它加密
			string value = FormsAuthentication.Encrypt(ticket);

			// 存入cookie
			cookie = new HttpCookie(FormsAuthentication.FormsCookieName, value);

			// 取得return url
			string url = FormsAuthentication.GetRedirectUrl(account, true);
			return url;
		}

		[Authorize]
		public ActionResult Logout()
		{
			Session.Abandon();
			FormsAuthentication.SignOut();
			return Redirect("/Members/Login");
		}
	}
}

ShoppingSite_FrontEnd.Site/Controllers/NewsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ShoppingSite_FrontEnd.Site.Models.EFModels;

namespace ShoppingSite_FrontEnd.Site.Controllers
{
	public class NewsController : Controller
	{
		private AppDbContext db = new AppDbContext();

		public ActionResult Index()
		{
			return View(db.News.ToList());
		}

	}
}

ShoppingSite_FrontEnd.Site/Controllers/PollsController.cs
using ShoppingSite_FrontEnd.Site.Models.Core.Interfaces;
using ShoppingSite_FrontEnd.Site.Models.Core.Services;
using ShoppingSite_FrontEnd.Site.Models.EFModels;
using ShoppingSite_FrontEnd.Site.Models.Infrastructures.ExtMethods;
using ShoppingSite_FrontEnd.Site.Models.Infrastructures.Repositories;
using ShoppingSite_FrontEnd.Site.Models.ValueObjects;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ShoppingSite_FrontEnd.Site.Controllers
{
	public class PollsController : Controller
	{
		private PollService _PollsService;
		public PollsController()
		{
			var db = new AppDbContext();
			string connString = @"server=.\sql2019;user id=sa5;password=sa5;initial catalog=Project";
			IPollRepository repo = new PollRepository(connString, db);
			_PollsService = new PollService(repo);
		}

		public ActionResult Index()
		{
			var data = _PollsService.SearchVoteResults().Select(x => x.ToPollVM());
			return View(data);
		}

		public ActionResult Vote()
		{
			var data = _PollsService.SearchVoteResults().Select(x => x.ToPollVM());
			return View(data);
		}

		public ActionResult UpdateVote(int productId, int qty)
		{
			_PollsService.UpdateVote(productId, qty);

			return new EmptyResult();
		}

		public ActionResult ErrDevBar()
		{
			//TODO:建立X軸用以統計月份
			string[] ProductName = { "五香乖乖", "椰子乖乖" };
			ViewBag.MonthLabel = ProductName;
			List<ModelChartJs> Dev = new List<ModelChartJs>
						{
								new ModelChartJs
								{
										Dev="五香乖乖",
										ErrCount = new int[]
										{
											20
										}
								},
								new ModelChartJs
								{
										Dev="椰子乖乖",
										ErrCount = new int[]
										{
											50
										}
								}
						};
			return View(Dev);
		}
	}
}

ShoppingSite_FrontEnd.Site/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>@ViewBag.Title - 我的 ASP.NET 應用程式</title>
  @Styles.Render("~/Content/css")
  @Scripts.Render("~/bundles/modernizr")
  <link href="~/Content/bootstrap.css" rel="stylesheet" />
  <link href="~/Content/bootstrap-responsive.css" rel="stylesheet" />
  <link href="~/Content/bootstrappage.css" rel="stylesheet" />
  <link href="~/Content/flexslider.css" rel="stylesheet" />
  <link href="~/Content/main.css" rel="stylesheet" />

  <style>
    #top-bar .user-menu li {
      border-right: none;
    }
  </style>
</head>
<body>
  <div id="top-bar" class="container">
    <div class="row">
      <div class="span4">
        <div class="sns">
          <ul class="user-menu">
            <li><a href="#"><img src="~/Assest/facebook.png" alt="" /></a></li>
            <li><a href="#"><img src="~/Assest/instagram.png" alt="" /></a></li>
            <li><a href="#"><img src="~/Assest/line.png" alt="" /></a></li>
            <li><a href="#"><img src="~/Assest/twitter.png" alt="" /></a></li>
          </ul>
        </div>
      </div>
      <div class="span8">
        <div class="account pull-right">
          <ul class="user-menu">
            <li>@Html.ActionLink("首頁", "Index", "Home")</li>
            <li>@Html.ActionLink("最新消息", "Index", "News")</li>
            <li>@Html.ActionLink("常見問題", "Index", "Faqs")</li>
            <li>@Html.ActionLink("商品投票", "Index", "Polls")</li>
            @{
              if (User.Identity.IsAuthenticated)
              {
                <li>Hi! @(User.Identity.Name)</li>
                <li>@Html.ActionLink("登出", "Logout", "Members")</li>
                <li><a href="/Cart/Info/"><i class="fas fa-shopping-cart"></i>購物車</a></li>
              }
              else
              {
                <li>@Html.ActionLink("登入", "Login", "Members")</li>
                <li>@Html.ActionLink("註冊", "Register", "Members")</li>
              }
            }
          </ul>
        </div>
      </div>
    </div>
  </div>
  <div id="wrapper" class="container">
    <section class="navbar main-menu">
      <div class="navbar-inner main-menu">
        <a href="/Home/Index/" class="logo pull-left"><img src="~/Assest/logo.png" class="site_logo" alt=""></a>
        <nav id="menu" class="pull-right">
          <ul>
            <li>@Html.ActionLink("所有商品", "Index", "Product")</li>
            <li>@Html.ActionLink("餅乾", "Cookies", "Product")</li>
            <li>@Html.ActionLink("糖果", "Candies", "Product")</li>
            <li>@Html.ActionLink("泡麵", "InstantNoodles", "Product")</li>
            <li>@Html.ActionLink("酒精飲料", "SoftDrinks", "Product")</li>
            <li>@Html.ActionLink("酒精飲料", "HardDrinks", "Product")</li>
          </ul>
        </nav>
      </div>
    </section>

    @RenderBody()

    <section id="footer-bar">
      <div class="row">
        <div class="span3">
          <h4>Navigation</h4>
          <ul class="nav">
            <li><a href="./index.html">Homepage</a></li>
            <li><a href="./about.html">About Us</a></li>
            <li><a href="./contact.html">Contac Us</a></li>
            <li><a href="./cart.html">Your Cart</a></li>
            <li><a href="./register.html">Login</a></li>
          </ul>
        </div>
        <div class="span4">
          <h4>My Account</h4>
          <ul class="nav">
            <li><a href="#">My Account</a></li>
            <li><a href="#">Order History</a></li>
            <li><a href="#">Wish List</a></li>
            <li><a href="#">Newsletter</a></li>
          </ul>
        </div>
        <div class="span5">
          <p class="logo"><img src="themes/images/logo.png" class="site_logo" alt=""></p>
          <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. the  Lorem Ipsum has been the industry's standard dummy text ever since the you.</p>
          <br />
          <span class="social_icons">
            <a class="facebook" href="#">Facebook</a>
            <a class="twitter" href="#">Twitter</a>
            <a class="skype" href="#">Skype</a>
            <a class="vimeo" href="#">Vimeo</a>
          </span>
        </div>
      </div>
    </section>
    <section id="copyright">
      <span>Copyright 2013 bootstrappage template  All right reserved.</span>
    </section>
  </div>

  @Scripts.Render("~/bundles/jquery")
  @Scripts.Render("~/bundles/bootstrap")
  @RenderSection("scripts", required: false)
  <script src="~/Scripts/bootstrap.js"></script>
  <script src="~/Scripts/jquery.fancybox.js"></script>
  <script src="~/Scripts/jquery.scrolltotop.js"></script>
  <script src="~/Scripts/superfish.js"></script>
  <script src="~/Scripts/common.js"></script>
  <script src="~/Scripts/jquery.flexslider-min.js"></script>
  <script type="text/javascript">
    function getCookie(name) {
      // Split cookie string and get all individual name=value pairs in an array
      var cookieArr = document.cookie.split(";");
      // Loop through the array elements
      for (var i = 0; i < cookieArr.length; i++) {
        var cookiePair = cookieArr[i].split("=");
        /* Removing whitespace at the beginning of the cookie name
        and compare it with the given string */
        if (name == cookiePair[0].trim()) {
          // Decode the cookie value and return
          return decodeURIComponent(cookiePair[1]);
        }
      }
      // Return null if not found
      return null;
    }

    $(function () {
      $(document).ready(function () {
        $('.flexslider').flexslider({
          animation: "fade",
          slideshowSpeed: 4000,
          animationSpeed: 600,
          controlNav: false,
          directionNav: true,
          controlsContainer: ".flex-container" // the container that holds the flexslider
        });
      });
    });
  </script>
</body>
</html>